version: "3.9"  # optional since v1.27.0
services:
  tvmazeworker:
    build:
        context: .
        dockerfile: TvMazeWorkerService/Dockerfile
    links:
      - mongo
  tvmazeapi:
    build:
        context: .
        dockerfile: TvMazeWebApi/Dockerfile
    ports:
      - "180:80"
      - "1443:443"
    environment:
        ASPNETCORE_ENVIRONMENT: Development 
    links:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
